- app/index.html
- app/scripts/app.js
- app/scripts/config.json
- app/scripts/contrib/Cesium/CesiumView.js
- app/scripts/contrib/Cesium/CesiumViewModule.js
- app/scripts/init.js
- app/scripts/main.js
- app/scripts/models/NavBarItemModel.js
- app/scripts/views/NavBarItemView.js
- app/styles/main.scss
- app/styles/social.scss
Defined variables for required paths centrally in index.html.
Provided a variable to allow additional items on navigation bar.
> Configuration centralization

- app/scripts/contrib/Cesium/CesiumView.js
> Embedded colormap (update for custom model)

- app/scripts/contrib/Cesium/CesiumView.js
Added check to only activate colorscale if in custom model also am sh…c file has been provided
> Update to embedded colorscale

- app/scripts/app.js
- app/scripts/config.json
- app/scripts/contrib/AVViewer/AVView.js
- app/scripts/contrib/Cesium/CesiumView.js
- app/scripts/controller/ContentController.js
- app/scripts/controller/DataController.js
- app/scripts/controller/DifferenceController.js
- app/scripts/controller/LayerController.js
- app/scripts/views/DownloadFilterView.js
- app/scripts/views/LayerItemView.js
- app/scripts/views/LayerSelectionView.js
- app/scripts/views/LayerSettings.js
- app/scripts/views/TimeSliderView.js
- app/styles/analyticsviewer.scss
- app/styles/layersettings.scss
- app/styles/timeslider.scss
- app/templates/CheckBoxOverlayLayer.hbs
- app/templates/DownloadFilter.hbs
- app/templates/LayerControl.hbs
- app/templates/LayerSettings.hbs
- app/templates/UseCase_MagneticModels.hbs
- app/templates/UseCase_SwarmAnalytics.hbs
- app/templates/wps_fetchData.hbs
- bower.json
* Updates to Layer panel which now introduces separation of satellite and product selection for swarm products
* Updated to analytics viewer
* Updated to how data is fetch allowing merging of different data types
* Bug solving
> Merged product download

- app/scripts/contrib/Cesium/CesiumView.js
- app/scripts/util.js
- app/scripts/views/DownloadFilterView.js
- app/scripts/views/LayerSelectionView.js
- app/scripts/views/LayerSettings.js
> Issuesresolve

- app/scripts/app.js
- app/scripts/communicator.js
- app/scripts/config.json
- app/scripts/contrib/AVViewer/AVView.js
- app/scripts/contrib/Cesium/CesiumView.js
- app/scripts/controller/ContentController.js
- app/scripts/controller/DataController.js
- app/scripts/core/SplitView/SplitViewController.js
- app/scripts/util.js
- app/scripts/views/DownloadFilterView.js
- app/scripts/views/LayerItemView.js
- app/scripts/views/LayerSelectionView.js
- app/scripts/views/LayerSettings.js
- app/scripts/views/TimeSliderView.js
- app/styles/analyticsviewer.scss
- app/styles/main.scss
- bower.json
Functionality to save status of workspace implemented, user gets notified if a previous version is loaded with the possiblity to reset to default settings.
> Save workspace (I210)

- app/scripts/config.json
- app/scripts/contrib/Cesium/CesiumView.js
Now we have geographic and magnetic graticules as well as simplified black coastlines + light country contours
> Changed available overlays 

- app/scripts/app.js
- app/scripts/config.json
- app/scripts/contrib/Cesium/CesiumView.js
- app/scripts/views/DownloadFilterView.js
- app/scripts/views/LayerItemView.js
- app/scripts/views/LayerSelectionView.js
- app/styles/main.scss
- app/templates/LayerControl.hbs
Added support for:
* TEC
* FAC
* EEF
> Added new data in preparation for service release 2.0

- app/scripts/views/DownloadFilterView.js
> Better process check

- app/scripts/contrib/AVViewer/AVView.js
- app/scripts/contrib/Cesium/CesiumView.js
- app/styles/analyticsviewer.scss
> Removed unused onResize functions from Cesium and AnalyticsView

- app/scripts/app.js
- app/scripts/communicator.js
- app/scripts/config.json
- app/scripts/contrib/Cesium/CesiumView.js
- app/scripts/views/LayerItemView.js
- app/scripts/views/LayerSettings.js
- app/templates/LayerSettings.hbs
- app/templates/wps_eval_model_diff.hbs
Introduced possibility to calculate residuals for models. In the settings panel a new drop down provides the possiblity to select which model to calculate the difference to.
> Model difference

- app/scripts/contrib/Cesium/CesiumView.js
- app/templates/FilterTemplate.hbs
> Moving bug fixes to production

- app/scripts/app.js
- app/scripts/contrib/Cesium/CesiumView.js
- app/scripts/controller/DataController.js
Shows now the direction vectors to the connected GPS satellites color encoded based on selected parameter
> Updated visualization of TEC data,

- app/scripts/app.js
- app/scripts/contrib/Cesium/CesiumView.js
- app/scripts/controller/DataController.js
Shows now the direction vectors to the connected GPS satellites color encoded based on selected parameter
> Updated visualization of TEC data

- app/scripts/config.json
Adding the F10.7 index layer and time-slider display.
> Adding F10.7 index to layers.

- app/scripts/config.json
Upgrading the Chaos-6-Core model to the latest X7 version.
> CHAOS-6 Core upgrade

- app/scripts/app.js
- app/scripts/config.json
- app/scripts/contrib/AVViewer/AVView.js
- app/scripts/controller/DataController.js
Adding support for the new Swarm EFIx_LP plasma products and removing the discontinued EFIx_PL.
Tested on testing.
Do not deploy before the EFIx_LP products become available on the server.
> Support for EFIx_LP replacing EFIx_PL

- app/scripts/app.js
- app/scripts/config.json
- app/scripts/contrib/AVViewer/AVView.js
- app/scripts/controller/DataController.js
> production release (VirES v2.2.2)

- app/scripts/app.js
- app/scripts/config.json
- app/scripts/contrib/AVViewer/AVView.js
- app/scripts/contrib/Cesium/CesiumView.js
- app/scripts/controller/DataController.js
- app/scripts/globals.js
- app/scripts/models/MagneticModelCollection.js
- app/scripts/views/LayerSettings.js
- app/scripts/views/TimeSliderView.js
- app/templates/wps_getModelInfo.hbs
This PR addresses #263 
The magnetic model validity is no more manually configured but retrieved from the server.
The model validity in the client thus stay in sync with the actual validity of the model used by the server.
In addition, validity is now displayed also for the custom model.
> Model validity fix

- app/scripts/app.js
- app/scripts/config.json
- app/scripts/controller/DataController.js
This PR adds support for the CHAOS-6 MMA models to the client.
Related to https://github.com/ESA-VirES/VirES-Server/pull/98
> support for the CHAOS-6 MMA models

- app/scripts/contrib/AVViewer/AVView.js
- app/scripts/contrib/Cesium/CesiumView.js
- app/scripts/contrib/Cesium/CesiumViewController.js
- app/scripts/views/TimeSliderView.js
- app/styles/timeslider.scss
> Multiple small fixes

- app/scripts/contrib/Cesium/CesiumView.js
- app/styles/cesium.scss
**Add forms for manual bbox insert.** 
- Performs form validation, north - south / west-east input order does not matter.
- Submit forms on enter or click of confirm button.
> Bbox input

- app/scripts/controller/DataController.js
- app/scripts/views/DownloadFilterView.js
- app/templates/DownloadProcess.hbs
The PR exposes the product traceability for the downloaded files returned by the VirES server.
- A link to product traceability is displayed in the download process parameters.
- Traceability of the `fetch_data` requests is not yet displayed.
Requires https://github.com/ESA-VirES/VirES-Server/pull/108
> Source Product Traceability

- app/scripts/config.json
- app/scripts/contrib/Cesium/CesiumView.js
- app/scripts/controller/DataController.js
- app/scripts/httpRequest.js
- app/scripts/util.js
- app/scripts/views/LayerSettings.js
- app/styles/cesium.scss
- app/styles/layersettings.scss
- app/templates/FieldlinesLabel.hbs
- app/templates/wps_get_field_lines.hbs
- fieldline data now retrieved as messagepack
- messagepack behaviour united
- click on fieldline shows information about ground points and apex point
- new fieldlines are not fetched from server when only style changed
- fieldline points color now computed in client
requires https://github.com/ESA-VirES/VirES-Server/pull/109
> Enhanced fieldlines

- app/scripts/contrib/AVViewer/AVView.js
- app/scripts/controller/DataController.js
- app/scripts/init.js
- app/scripts/main.js
- app/scripts/views/LayerSettings.js
- bower.json
- `graphly` update solving line plotting issues
> Line plotting fix

- Gruntfile.js
- app/index.html
- app/scripts/app.js
- app/scripts/config.json
- app/scripts/controller/ContentController.js
- app/scripts/controller/DataController.js
- app/scripts/controller/DownloadController.js
- app/scripts/globals.js
- app/scripts/init.js
- app/scripts/models/UserDataCollection.js
- app/scripts/views/LayerItemView.js
- app/scripts/views/LayerSelectionView.js
- app/scripts/views/TimeSliderView.js
- app/styles/main.scss
- app/templates/LayerControl.hbs
- app/templates/NavBar.hbs
- bower.json
- Custom data upload and later visualization as a new satellite U
> Data upload

- app/scripts/app.js
- app/scripts/config.json
- app/scripts/contrib/Cesium/CesiumView.js
- app/scripts/controller/DataController.js
- app/scripts/views/TimeSliderView.js
- TimeSlider now shows uploaded data always and not product-wise
> TimeSlider uploaded data update

- app/scripts/app.js
- app/scripts/communicator.js
- app/scripts/config.json
- app/scripts/contrib/AVViewer/AVView.js
- app/scripts/contrib/Cesium/CesiumView.js
- app/scripts/controller/ContentController.js
- app/scripts/controller/DataController.js
- app/scripts/globals.js
- app/scripts/init.js
- app/scripts/util.js
- app/scripts/views/LayerItemView.js
- app/scripts/views/LayerSelectionView.js
- bower.json
Key features:
- re-worked client-state handling
- client-state import/export
- client invocation with a predefined state
> Reworked client state handling and its import/export.

- app/scripts/app.js
- app/scripts/config.json
- app/scripts/contrib/AVViewer/AVView.js
- app/scripts/controller/ContentController.js
- app/scripts/controller/DataController.js
- app/scripts/controller/UploadController.js
- app/scripts/models/UserDataCollection.js
- app/scripts/util.js
- app/scripts/views/LayerSelectionView.js
- app/scripts/views/TimeSliderView.js
- app/scripts/views/UploadView.js
- app/styles/main.scss
- app/styles/upload.scss
- app/templates/Download.hbs
- app/templates/DownloadFilter.hbs
- app/templates/Info.hbs
- app/templates/LayerControl.hbs
- app/templates/LayerSettings.hbs
- app/templates/OptionsControl.hbs
- app/templates/SelectionManager.hbs
- app/templates/ToolControl.hbs
- app/templates/UIElement.hbs
- app/templates/Upload.hbs
- app/templates/UploadItem.hbs
- app/templates/UploadManager.hbs
- app/templates/UploadParameter.hbs
- app/templates/iFrame.hbs
see https://github.com/ESA-VirES/VirES-Server/pull/124
> Upload extra constant fields

- app/scripts/controller/DataController.js
This PR fixes #372 in the production branch.
> Hot-fix: Showing labels for periodic latitudes

- app/scripts/app.js
- app/templates/Info.hbs
- app/templates/UploadManager.hbs
Client changes required by https://github.com/ESA-VirES/VirES-Server/pull/132
> New Service Terms and Privacy Notice - URL

- app/scripts/models/LayerModel.js
> Filling in default parameters when generating request model expression

- LICENSE
- app/scripts/contrib/Cesium/CesiumView.js
- app/scripts/globals.js
- app/scripts/init.js
Key features:
- Filling in default parameters in model requests (#382)
> production release (VirES v3.1.2)

- app/scripts/config.json
- app/scripts/globals.js
- app/templates/Info.hbs
This hotfix PR updates the IGRF model to its latest 13th generation.
Related to https://github.com/ESA-VirES/VirES-Server/pull/138
> Hotfix: IGRF-13

- app/scripts/contrib/Cesium/CesiumView.js
- app/scripts/views/LayerSettings.js
- Fixes magnetic model legend not displayed in cesium
- avoid crash on random plotty not loaded early enough problem (layersettings)
> Cesium legend model

- app/scripts/app.js
- app/scripts/config.json
- app/scripts/contrib/AVViewer/AVView.js
- app/scripts/contrib/Cesium/CesiumView.js
- app/scripts/contrib/Cesium/CesiumViewModule.js
- app/scripts/contrib/MapViewer/MapViewModule.js
- app/scripts/contrib/VirtualGlobeViewer/VirtualGlobeViewModule.js
- app/scripts/globals.js
- app/scripts/init.js
- app/scripts/views/LayerSettings.js
- app/styles/analyticsviewer.scss
- app/styles/timeslider.scss
- app/templates/Info.hbs
- bower.json
Key features:
- mostly minor fixes and version bump
Required by https://github.com/ESA-VirES/VirES-Server/pull/148
> production release (VirES v3.2.0)

- app/scripts/config.json
- app/scripts/contrib/AVViewer/AVView.js
- app/scripts/controller/DataController.js
see related https://github.com/ESA-VirES/VirES-Server/pull/150
> Adding dDst index.

- app/scripts/config.json
related to https://github.com/ESA-VirES/VirES-Server/pull/152
> Adding support for the MLI_SHA_2E model.

- app/scripts/config.json
- app/scripts/contrib/AVViewer/AVView.js
- app/scripts/controller/DataController.js
- app/scripts/globals.js
- app/scripts/init.js
- app/scripts/models/LayerModel.js
- app/scripts/views/DownloadFilterView.js
- app/scripts/views/LayerSettings.js
- app/templates/DownloadProcess.hbs
- app/templates/Info.hbs
Key features:
- adding AMPS model
- adding MLI_SHA_2E model
- adding composed models + exclusive model selection
- adding dDst index
related to https://github.com/ESA-VirES/VirES-Server/pull/153
> production release (VirES v3.3.0)

- app/scripts/app.js
- app/scripts/views/DownloadFilterView.js
This PR fixes following issues:
- Kp, Dst, dDst, F10 indices not available for filtering in the Download panel #423
- VirES client fails to load in MS Edge 44.x browser #425
> Hotfix: various fixes

- app/scripts/contrib/Cesium/CesiumView.js
- app/scripts/viresDataRequest.js
- app/templates/wps_fetchFieldlines.hbs
Switching to the new field-lines WPS process.
See related https://github.com/ESA-VirES/VirES-Server/pull/160
> VIR-350: new fieldlines API

- app/scripts/app.js
- app/scripts/communicator.js
- app/scripts/config.json
- app/scripts/contrib/AVViewer/AVView.js
- app/scripts/contrib/Cesium/CesiumView.js
- app/scripts/contrib/Cesium/CesiumViewController.js
- app/scripts/controller/ContentController.js
- app/scripts/controller/DataController.js
- app/scripts/globals.js
- app/scripts/init.js
- app/scripts/util.js
- app/scripts/views/DownloadFilterView.js
- app/scripts/views/TimeSliderView.js
- app/scripts/viresDataRequest.js
- app/styles/download.scss
- app/templates/Info.hbs
- app/templates/wps_fetchData.hbs
- app/templates/wps_fetchFieldlines.hbs
- app/templates/wps_fetchFilteredData.hbs
- app/templates/wps_fetchFilteredDataAsync.hbs
- bower.json
Key features:
- plotting peak and boundary symbols in the VA panel.
- plotting of the satellites' orbits
- using new fieldlines API
- minor fixes and improvements
- using S2 cloudless 2020
related to https://github.com/ESA-VirES/VirES-Server/pull/164
> production release (VirES v3.5.0)

- app/scripts/contrib/Cesium/CesiumView.js
see https://github.com/ESA-VirES/WebClient-Framework/issues/446
> Fetch orbits from the MODx_SC collections.

- app/scripts/app.js
- app/scripts/config.json
- app/scripts/contrib/AVViewer/AVView.js
- app/scripts/controller/DataController.js
- app/scripts/views/LayerSettings.js
related to https://github.com/ESA-VirES/VirES-Server/pull/189
> Implementing support for EFIxIDM_2_ products

- .bowerrc
- .gitignore
- Gruntfile.js
- package-lock.json
- package.json
- readme.md
> Fixing client build

- app/scripts/views/DownloadFilterView.js
- app/scripts/views/DownloadFilters.js
- app/styles/download.scss
- app/templates/BitmaskFilterTemplate.hbs
- app/templates/DateRangeFilterTemplate.hbs
- app/templates/DownloadFilter.hbs
- app/templates/DurationFilterTemplate.hbs
- broken input validation #466
- broken datepickers #484
- style improvements
> Fixing download panel filters
